### ISSUE TITLE
the brute-force raymarching transmittance and analytical transmittance seems difference

### ISSUE THREAD

**Issue by chena1982** [k-ishiyama/toymodels#1]
Is the transmittance's analytical formula has some bug?
Or i get something wrong?

the brute-force raymarching transmittance:
![transmittance1](https://user-images.githubusercontent.com/5953033/38488267-7c0e3302-3c15-11e8-89b6-c9e82973210d.png)

analytical transmittance:
![transmittance2](https://user-images.githubusercontent.com/5953033/38488361-cc2aaa14-3c15-11e8-96de-3ffa2528b3cd.png)

http://www.iquilezles.org/www/articles/fog/fog.htm
The analytical formula in that article is difference with yours.

Thanks.

**Comment by chena1982** [comment]
PS, mMieSctrCoeff multiply 1e-3f, but why mMieAbsorption don't multiply 1e-3f?

**Comment by k-ishiyama** [comment]
Now I am reorganizing the code, so I think that the transmittance you pointed out is temporarily gone.
I will answer your question on the weekend.

**Comment by chena1982** [comment]
sorry, the analytical formula is same.

**Comment by k-ishiyama** [comment]
No problem.

> PS, mMieSctrCoeff multiply 1e-3f, but why mMieAbsorption don't multiply 1e-3f?

This is because I defined mMieAbsorption as a multiple of the scattering coefficient.
However it did not match the context of the scattering theory, so I will fix it.
Thank you for pointing it out!
